services:
  - type: web
    name: telegram-v2ray-bot
    env: python
    buildCommand: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      export PATH="$HOME/.cargo/bin:$PATH"
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python telegram-v2ray-bot/main.py
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
